<?php

use Cissee\Webtrees\Module\PersonalFacts\IndividualFactsTabModuleExtended;
use Fisharebest\Webtrees\Auth;
use Fisharebest\Webtrees\Elements\UnknownElement;
use Fisharebest\Webtrees\Elements\XrefAssociate;
use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\Gedcom;
use Fisharebest\Webtrees\GedcomRecord;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Media;
use Fisharebest\Webtrees\Module\ModuleChartInterface;
use Fisharebest\Webtrees\Module\ModuleInterface;
use Fisharebest\Webtrees\Module\RelationshipsChartModule;
use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\Services\ModuleService;
use Fisharebest\Webtrees\Services\RelationshipService;
use Fisharebest\Webtrees\View;
use Vesta\Model\PlaceStructure;
use Vesta\VestaUtils;

/**
 * @var Fact                             $fact
 * @var GedcomRecord                     $record
 * @var IndividualFactsTabModuleExtended $module
 */

$parent  = $fact->record();
$tree    = $parent->tree();
[, $tag] = explode(':', $fact->tag());
$label   = $fact->label();
$value   = $fact->value();
$type    = $fact->attribute('TYPE');
$id      = $fact->id();

$element = Registry::elementFactory()->make($fact->tag());

// New or deleted facts need different styling
$styles = [];
if ($fact->isPendingAddition()) {
    $styles[] = 'wt-new';
}
if ($fact->isPendingDeletion()) {
    $styles[] = 'wt-old';
}

//[RC] added
$styles = array_merge($styles, $module->additionalStyles($fact));

//[RC] PATCHED change style in order to keep separate from original module
// Event of close relative
if ($tag === 'EVEN' && $value === 'CLOSE_RELATIVE') {
    $value    = '';
    $styles[] = 'wt-relation-fact-pfh collapse';
}

//[RC] PATCHED change style in order to keep separate from original module
// Event of close associates
if ($id === 'asso') {
    $styles[] = 'wt-associate-fact-pfh collapse';
}

if ($element instanceof UnknownElement && $tree->getPreference('HIDE_GEDCOM_ERRORS') === '0') {
    $styles[] = 'd-none';
}

//[RC] PATCHED change style in order to keep separate from original module
// historical facts
if ($id === 'histo') {
    $styles[] = 'wt-historic-fact-pfh collapse';
}

// Use marriage type as the label.  e.g. "Civil partnership"
if ($tag === 'MARR') {
    $label = $fact->label();
    $type  = '';
}

?>
<tr class="<?= implode(' ', $styles) ?>">
    <th scope="row">
            
        <?php
            //[RC] added additional edit controls, even if fact itself is not editable
            $additionalControls = $module->gveAdditionalEditControls($fact);
            $main = $additionalControls->getMain(); //echoed further down
            $script = $additionalControls->getScript();
            
            if ($script !== '') {
                View::push('javascript');
                echo $script;
                View::endpush();
            }            
        ?>
        
        <?php
        //[RC] adjusted: asso gets special extended label
        //this could be (partially) in main webtrees
        
        //check: anything else than Individual actually possible here?
        if (($fact->id() === 'asso') && ($record instanceof Individual)) {
            $labelForAsso = $module->gveLabelForAsso($label, $fact, $record);
            $label = $labelForAsso->getMain(); //echoed further down
            $script = $labelForAsso->getScript();
            
            if ($script !== '') {
                View::push('javascript');
                echo $script;
                View::endpush();
            }
        }
        
        ?>
        <div class="wt-fact-label"><?= $label?></div>
            
        <?php
            //[RC] extended,
            //and sub view 'fact-edit-links' integrated
        
            //[RC] meh - why not just use a non-editable Fact subclass for asso/histo? (see VirtualFact)
            //rather hacky to have the special checks here!
            $originalCheck = ($id !== 'histo' && $id !== 'asso' && $fact->canEdit() && !in_array($tag, ['HUSB', 'WIFE', 'CHIL', 'FAMC', 'FAMS'], true));
            
            $adjustedCheck = ($id !== 'histo' && (($id !== 'asso' && $fact->canEdit()) || ($main != '')) && !in_array($tag, ['HUSB', 'WIFE', 'CHIL', 'FAMC', 'FAMS'], true));
        ?>  
        <?php if ($adjustedCheck) : ?>
            <div class="pt-2 wt-fact-edit-links">
                <?php if ($originalCheck) : ?>                
                    <?= view('edit/icon-fact-edit', ['fact' => $fact, 'url' => $record->url() ?? null]) ?>
                    <?= view('edit/icon-fact-copy', ['fact' => $fact]) ?>
                    <?= view('edit/icon-fact-delete', ['fact' => $fact]) ?>                
                <?php endif ?>
                <?= $main ?>
            </div>
        <?php endif ?>

        <?php if ($tree->getPreference('SHOW_FACT_ICONS')) : ?>
            <span class="wt-fact-icon wt-fact-icon-<?= e($tag) ?>" title="<?= strip_tags($label) ?>"></span>
        <?php endif ?>
    </th>

    <td>
        <?php if ($fact->target() instanceof Media) : ?>
            <div class="d-flex">
                <?php foreach ($fact->target()->mediaFiles() as $media_file) : ?>
                    <?= $media_file->displayImage(100, 100, 'contain', []) ?>
                <?php endforeach ?>
            </div>

            <a href="<?= e($fact->target()->url()) ?>"><?= $fact->target()->fullName() ?></a>

            <?php foreach ($fact->target()->facts(['NOTE']) as $note) : ?>
                <?= view('fact-gedcom-fields', ['gedcom' => $note->gedcom(), 'parent' => $fact->target()->tag(), 'tree' => $fact->record()->tree()]) ?>
            <?php endforeach ?>
        <?php else : ?>
            <div class="wt-fact-main-attributes">
                <?php if ($parent !== $record) : ?>
                    <div class="wt-fact-record">
                        <?php if ($parent instanceof Family) : ?>
                            <?php foreach ($parent->spouses()->filter(static fn ($individual): bool => $individual !== $record) as $spouse) : ?>
                                <a href="<?= e($spouse->url()) ?>"><?= $spouse->fullName() ?></a> —
                            <?php endforeach ?>
                            <a href="<?= e($parent->url()) ?>"><?= I18N::translate('View this family') ?></a>
                        <?php elseif ($parent instanceof Individual) : ?>
                            <a href="<?= e($parent->url()) ?>"><?= $parent->fullName() ?></a>
                        <?php endif ?>
                    </div>
                <?php endif ?>

                <div class="wt-fact-value">
                    <?= $element->value($value, $tree) ?>
                    <?php if ($element instanceof XrefAssociate && $fact->target() instanceof Individual) : ?>
                        <?php
                        $relationshipChartModule = app(ModuleService::class)->findByComponent(ModuleChartInterface::class, $tree, Auth::user())
                            ->first(static fn (ModuleInterface $m):bool => $m instanceof RelationshipsChartModule)
                        ?>

                        <?php if ($relationshipChartModule instanceof RelationshipsChartModule) : ?>
                            — <a href="<?= $relationshipChartModule->chartUrl($fact->target(), ['xref2' => $record->xref()]) ?>" rel="nofollow">
                                <?= app(RelationshipService::class)->getCloseRelationshipName($fact->target(), $record) ?>
                            </a>
                        <?php endif ?>
                    <?php endif ?>
                </div>

                <!-- Type of this fact/event (allow user-translations) -->
                <?php if ($type !== '' && $tag !== 'EVEN' && $tag !== 'FACT') : ?>
                    <div class="wt-fact-type">
                        <?= Registry::elementFactory()->make($fact->tag() . ':TYPE')->labelValue(I18N::translate($type), $tree) ?>
                    </div>
                <?php endif ?>

                <?= view('fact-date', ['cal_link' => 'true', 'fact' => $fact, 'record' => $record, 'time' => true]) ?>
                
                <div class="wt-fact-place">
                    <?= view(VestaUtils::vestaViewsNamespace() . '::fact-place-actual', [
                        'ps' => PlaceStructure::fromFact($fact), 
                        'module' => $module,
                        'useVestals' => $module->useVestals()]) ?>
                    
                    <?php
                        //[RC] why are the following tags within wt-fact-place? they have nothing to do with PLAC?
                        //anyway: no changes wrt original view
                    ?>
                    
                    <?= view(VestaUtils::vestaViewsNamespace() . '::fact-other', ['fact' => $fact, 'record' => $record]) ?>
                </div>
            </div>

            <div class="wt-fact-other-attributes mt-2">
                <?php preg_match_all('/\n2 (' . Gedcom::REGEX_TAG . ')( .*)?((\n[3-9].*)*)/', $fact->gedcom(), $matches, PREG_SET_ORDER) ?>
                <?php foreach ($matches as $match) : ?>
                    <?php if (!in_array($match[1], ['DATE', 'AGE', 'HUSB', 'WIFE', 'PLAC', 'ASSO', '_ASSO', 'STAT', 'TEMP', 'TYPE', 'CONT', 'NOTE', 'OBJE', 'SOUR'], true)) : ?>
                        <?= view('fact-gedcom-fields', ['gedcom' => $match[0], 'parent' => $fact->tag() . ':' . $match[1], 'tree' => $tree]) ?>
                    <?php endif ?>
                <?php endforeach; ?>
            </div>

            <?php if ($id !== 'asso') : ?>
            
                <?php
                //[RC] adjusted
                ?>
                <?= view(VestaUtils::vestaViewsNamespace() . '::fact-associates', ['fact' => $fact, 'module' => $module]) ?>
            <?php endif ?>

            <?= view('fact-sources', ['fact' => $fact]) ?>
            <?= view('fact-notes', ['fact' => $fact]) ?>
            <?= view('fact-media', ['fact' => $fact]) ?>
        <?php endif ?>
    </td>
</tr>
