<?php

use Fisharebest\Webtrees\Module\ModuleInterface;
use Vesta\Model\PlaceStructure;
use Vesta\VestaUtils;

/**
 * @var PlaceStructure  $ps
 * @var ModuleInterface $module
 * @var bool            $hideCoordinates
 */

?>

<div class="wt-fact-place">
    <?= view(VestaUtils::vestaViewsNamespace() . '::fact-place-actual', [
        'ps' => $ps, 
        'module' => $module,
        'useVestals' => false,
        'hideCoordinates' => $hideCoordinates]) ?>
</div>
